Tarea 4/Controllers/ExcelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Excel = Microsoft.Office.Interop.Excel;
using System.IO;
using Tarea_4.Models;

namespace Tarea_4.Controllers
{
    public class ExcelController : Controller
    {
        // GET: Excel
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Import(HttpPostedFileBase excelfile)
        {
            if (excelfile == null || excelfile.ContentLength == 0)
            {
                ViewBag.Error = "Seleccione un archivo excel<br>";
                return View("Index");
            }
            else
            {
                if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx"))
                {
                    string path = Server.MapPath("~/Uploads/" + excelfile.FileName);
                    if (System.IO.File.Exists(path))
                        System.IO.File.Delete(path);
                    excelfile.SaveAs(path);

                    //Leer datos del archivo excel
                    Excel.Application application = new Excel.Application();
                    Excel.Workbook workbook = application.Workbooks.Open(path);
                    Excel.Worksheet worksheet = workbook.ActiveSheet;
                    Excel.Range range = worksheet.UsedRange;
                    List<ExcelModel> listaDatos = new List<ExcelModel>();
                    for (int row = 2; row <= range.Rows.Count; row++)
                    {
                        ExcelModel e = new ExcelModel();
                        e.Id = ((Excel.Range)range.Cells[row, 1]).Text;
                        e.Nombre = ((Excel.Range)range.Cells[row, 2]).Text;
                        e.Precio = decimal.Parse(((Excel.Range)range.Cells[row, 3]).Text);
                        e.Cantidad = int.Parse(((Excel.Range)range.Cells[row, 4]).Text);

                        listaDatos.Add(e);
                    }

                    ViewBag.ListaDatos = listaDatos;

                    return View("Success");
                }
                else
                {
                    ViewBag.Error = "Tipo de archivo es incorrecto<br>";
                    return View("Index");
                }

            }
        }
    }
}

Tarea 4/Views/Excel/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        .panel {
            margin-top: 35px;
            width: 313px;
        }

        .form-control {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="panel-title text-center">Lector de Archivos xls</h4>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm("Import", "Excel", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                <input type="file" name="excelfile" />
                @Html.Raw(ViewBag.Error)
                <br />

                <div class="text-center">
                    <input class="btn btn-primary" type="submit" value="Cargar" />
                </div>
            }
        </div>
    </div>


</body>
</html>

Tarea 4/Views/Excel/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>

    <div class="panel panel-info">
        <div class="panel-heading">
            <h4 class="panel-title text-center">Lista de Datos</h4>
        </div>
        <div class="panel-body">
            <table class="table" cellpadding="2" cellspacing="2" border="1">
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                </tr>
                @foreach (var d in ViewBag.ListaDatos)
                {
                    <tr>
                        <td>@d.Id</td>
                        <td>@d.Nombre</td>
                        <td>@d.Precio</td>
                        <td>@d.Cantidad</td>
                    </tr>
                }
            </table>
        </div>
    </div>

</body>
</html>