Tarea 4/Models/Filtro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Tarea_4.Models
{
    public class Filtro
    {
        public string filtro { get; set; }

        public enum FiltroContenido
        {
            Noticias, Musica, Peliculas
        }
    }
}

Tarea 4/Controllers/FiltroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tarea_4.Controllers
{
    public class FiltroController : Controller
    {
        // GET: Filtro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Musica()
        {
            return View();
        }

        public ActionResult Peliculas()
        {
            return View();
        }

        public ActionResult Noticias()
        {
            return View();
        }
    }
}

Tarea 4/Views/Filtro/Index.cshtml
@model Tarea_4.Models.Filtro

@{
    ViewBag.Title = "Index";
}

    <html>
    <head>
        <style>

            .dropdown-button {
                background-color: #00b351;
                color: white;
                padding: 16px;
                font-size: 16px;
                border: none;
            }

            .dropdown {
                position: relative;
                display: inline-block;
            }
            
            .dropdown-list {
                display: none;
                position: absolute;
                background-color: #f1f1f1;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                z-index: 1;
            }
                
                .dropdown-list a {
                    color: black;
                    padding: 12px 16px;
                    text-decoration: none;
                    display: block;
                    font-family: verdana;
                }
                    
                    .dropdown-list a:hover {
                        background-color: #ddd;
                    }
            
            .dropdown:hover .dropdown-list {
                display: block;
            }
            
            .dropdown:hover .dropdown-button {
                background-color: #6666ff;
            }
        </style>
    </head>
    <body>
        <div class="dropdown">
            <button class="dropdown-button">Filtro de Contenido</button>
            <div class="dropdown-list">
                <a href=@Url.Action("Noticias", "Filtro")>Noticias</a>
                <a href=@Url.Action("Musica", "Filtro")>Musica</a>
                <a href=@Url.Action("Peliculas", "Filtro")>Peliculas</a>
            </div>
            <a href="@Url.Action("Index", "Home")">Menu Principal</a>
        </div>
    </body>
    </html>

Tarea 4/Views/Filtro/Musica.cshtml
@{
    ViewBag.Title = "Musica";
}

<h1> Reproductor De Musica </h1>
<script>
function cambiarTrack(track) {
   var path =  track.getAttribute("path")
   viejo_audio = document.getElementById("reproductor")
   audio_padre = viejo_audio.parentNode
   audio_padre.removeChild(viejo_audio)
   nuevo_audio = document.createElement("audio")
   nuevo_audio.setAttribute("id","reproductor")
   nuevo_audio.setAttribute("controls", "controls")
  // nuevo_audio.setAttribute("autoplay", "autoplay")
   source = document.createElement("source")
   source.setAttribute("src", path)
   source.setAttribute("type", "audio/mpeg")
   source.setAttribute("id", "reproductorSource")
   nuevo_audio.appendChild(source)
   audio_padre.appendChild(nuevo_audio)}
function cargarReproductor() {
         var select = document.getElementById("selectTrack")
         var path = select.options[0].getAttribute("path")
   nuevo_audio = document.createElement("audio")
   nuevo_audio.setAttribute("id","reproductor")
   nuevo_audio.setAttribute("controls", "controls")
   source = document.createElement("source")
   source.setAttribute("src", path)
   source.setAttribute("type", "audio/mpeg")
   source.setAttribute("id", "reproductorSource")
   nuevo_audio.appendChild(source)
   padre = document.getElementById("reproductorBox")
   padre.appendChild(nuevo_audio)
}
</script>
<div id="reproductorBox"></div>
<select id="selectTrack" multiple onchange="cambiarTrack(this.options[this.selectedIndex]);">
    <option path="../music/Basura.mp3">Rata Blanca - Basura</option>
    <option path="../music/Get.mp3">Daft Punk - Get Lucky</option>
    <option path="../music/Wonderwall.mp3">Oasis - Wonderwall</option>
</select>
<script>cargarReproductor();</script>

<a href="@Url.Action("Index", "Home")">Menu Principal</a>

Tarea 4/Views/Filtro/Noticias.cshtml
@{
    ViewBag.Title = "Noticias";
}

<h1> Links de los periodicos mas importante tanto a nivel nacional como internacional</h1>
    <table class="egt">

        <tr>

            <th scope="row">Noticias</th>

            <th>Nacionales</th>

            <th>Internacionales</th>



        </tr>

        <tr>

            <th>Link #1</th>

            <td><a href=https://www.diariolibre.com/ >Diario Libre</a></td>

            <td><a href=https://www.nytimes.com/es/ >New York Times</a></td>



        </tr>

        <tr>

            <th>Link #2</th>

            <td><a href=https://elnacional.com.do/ > El nacional</a></td>

            <td><a href=https://elpais.com/america/ > El pais </a></td>

        </tr>

        <tr>

            <th>Link #3</th>

            <td><a href=https://listindiario.com/ > Listin Diario</a></td>

            <td><a href=https://www.lanacion.com.ar/ > La nacion </a></td>

        </tr>

        <tr>

            <th>Link #4</th>

            <td><a href=https://hoy.com.do/ > Hoy </a></td>

            <td><a href=https://www.theguardian.com/uk > The Guardian</a></td>

        </tr>

        <tr>

            <th>Link #5</th>

            <td><a href=https://www.elcaribe.com.do/ > El caribe</a></td>

            <td><a href=https://www.wsj.com/ > The wall street journal</a></td>


        </tr>

    </table>

    <a href="@Url.Action("Index", "Home")">Menu Principal</a>

Tarea 4/Views/Filtro/Peliculas.cshtml
@{
    ViewBag.Title = "Peliculas";
}

<h1> Accion </h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/vOUVVDWdXbo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<h1> Aventura </h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/BmmoX8MBmmk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<h1>Dramas </h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/jkC3POL66dg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<h1> Infantiles</h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/gn5QmllRCn4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<h1>Documentales </h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/34Kz-PP_X7c" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>